CREATE TABLE [dbo].[Room]
(
	[RoomId]	  INT IDENTITY(1,1) NOT NULL,
	[Name]		  VARCHAR(50) NOT NULL,	
	[CreatedOn]   DATETIME	NOT NULL,
	[UpdatedOn]   DATETIME	NULL,	
	[DeletedOn]   DATETIME NULL,
	CONSTRAINT [PK_dbo.Room] PRIMARY KEY CLUSTERED ([RoomId] ASC)	
) ON [PRIMARY]
