//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAwareAndRealTimeTimeTable.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupActivities = new HashSet<GroupActivity>();
            this.StudentGroups = new HashSet<StudentGroup>();
            this.CourseGroupSubjects = new HashSet<CourseGroupSubject>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int GroupId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int YearId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual ICollection<GroupActivity> GroupActivities { get; set; }
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
        public virtual Course Course { get; set; }
        public virtual Year Year { get; set; }
        public virtual ICollection<CourseGroupSubject> CourseGroupSubjects { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
