//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAwareAndRealTimeTimeTable.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ContextAwareAndRealTimeTimeTable.EF.Context;
    
    public partial class ContextAwareAndRealTimeTimeTableEntities : DbContext,IDbContext
    {
        public ContextAwareAndRealTimeTimeTableEntities()
            : base("name=ContextAwareAndRealTimeTimeTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupActivity> GroupActivities { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentGroup> StudentGroups { get; set; }
        public virtual DbSet<StudentSubject> StudentSubjects { get; set; }
        public virtual DbSet<StudentYear> StudentYears { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseSubject> CourseSubjects { get; set; }
        public virtual DbSet<SubjectYear> SubjectYears { get; set; }
        public virtual DbSet<CourseGroupSubject> CourseGroupSubjects { get; set; }
        public virtual DbSet<StudentCourse> StudentCourses { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
    }
}
