//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAwareAndRealTimeTimeTable.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentGroups = new HashSet<StudentGroup>();
            this.StudentSubjects = new HashSet<StudentSubject>();
            this.StudentYears = new HashSet<StudentYear>();
            this.StudentCourses = new HashSet<StudentCourse>();
        }
    
        public int StudentId { get; set; }
        public string StudentNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
        public virtual ICollection<StudentYear> StudentYears { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}
