//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAwareAndRealTimeTimeTable.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public Year()
        {
            this.StudentYears = new HashSet<StudentYear>();
            this.Groups = new HashSet<Group>();
            this.SubjectYears = new HashSet<SubjectYear>();
        }
    
        public int YearId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual ICollection<StudentYear> StudentYears { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<SubjectYear> SubjectYears { get; set; }
    }
}
