//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAwareAndRealTimeTimeTable.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseGroupSubjects = new HashSet<CourseGroupSubject>();
            this.CourseSubjects = new HashSet<CourseSubject>();
            this.Groups = new HashSet<Group>();
            this.StudentCourses = new HashSet<StudentCourse>();
        }
    
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual ICollection<CourseGroupSubject> CourseGroupSubjects { get; set; }
        public virtual ICollection<CourseSubject> CourseSubjects { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}
